stages:
  - commit
  - syntax
  - lint
  - build
  - test
  - coverage

rust-fmt:
  stage: syntax
  script:
    - rustup show
    - rustup component add rustfmt
    - cargo fmt -- --check
  image: rust:latest

rust-clippy:
  stage: lint
  script:
    - rustup show
    - rustup component add clippy
    - cargo check --all-features --tests
    - cargo clean
    - cargo clippy --all-features -- -D warnings
  image: rust:latest

rust-build:
  stage: build
  script:
    - rustup show
    - cargo build
  image: rust:latest

rust-test:
  stage: test
  script:
    - rustup show
    - cargo test
  image: rust:latest

rust-coverage:
  stage: coverage
  script:
    - cargo install cargo-tarpaulin
    - cargo tarpaulin -v
  image: rust:latest
