stages:
  - commit
  - syntax
  - lint
  - build
  - test
  - coverage

commit-convention:
  stage: commit
  script:
    - npm install
    - npm run commitlint
  image: node:latest

markdown-lint:
  stage: syntax
  script:
    - npm install
    - npm run markdownlint
  image: node:latest

rust-fmt:
  stage: syntax
  script:
    - rustup show
    - rustup component add rustfmt
    - cargo fmt -- --check
  image: rust:latest

rust-clippy:
  stage: lint
  script:
    - rustup show
    - rustup component add clippy
    - cargo check --all-features --tests
    - cargo clean
    - cargo clippy --all-features -- -D warnings
  image: rust:latest

rust-build:
  stage: build
  script:
    - rustup show
    - cargo build
  image: rust:latest

rust-test:
  stage: test
  script:
    - rustup show
    - cargo test
  image: rust:latest

rust-coverage:
  stage: coverage
  script:
    - rustup show
    - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
    - ./grcov --version
    - export CARGO_INCREMENTAL=0
    - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
    - export RUSTDOCFLAGS="-Cpanic=abort"
    - rustup install nightly
    - cargo +nightly build
    - cargo +nightly test
    - ./grcov ./target/debug/ -s . --commit-sha="${CI_COMMIT_SHA}" --llvm --branch --ignore-not-existing --ignore="/*" --ignore="*_tests.rs" --ignore="benches/*" -t html -o ./target/debug/coverage
    - cat ./target/debug/coverage/index.html
  image: rust:latest