[package]
name = "wisent"
version = "0.1.0"
authors = ["Davide Pizzolotto <davide.pizzolotto@gmail.com>"]
edition = "2018"
publish = false

[lib]
name = "libwisent"
path = "src/core/lib.rs"

[[bin]]
name = "wisent"
path = "src/main.rs"

[profile.release]
lto = "fat"

[profile.bench]
lto = "fat"