ignore:
   - "src/core/*_tests.rs"
   - "src/main.rs" # this is impossible to test so...
coverage:
  status:
    project:
      default:
        target: 95
        threshold: 0%
        base: auto
        paths:
          - "src/core"
        branches:
          - master
        if_ci_failed: error
