coverage:
  status:
    project:
      default:
        target: 95
        threshold: 0%
        base: auto
        paths:
          - "corelib/src"
        branches:
          - master
        if_ci_failed: error
