ignore:
   - "*_tests.rs"
coverage:
  status:
    project:
      default:
        target: 95
        threshold: 0%
        base: auto
        paths:
          - "src/core"
        branches:
          - master
        if_ci_failed: error
