use_field_init_shorthand = true
use_try_shorthand = true
imports_granularity = "Module"
newline_style = "Unix"
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "One"
array_width = 90
normalize_doc_attributes = true
wrap_comments = true
struct_lit_width = 35
