version: 2.1

executors:
  rust:
    docker:
      - image: circleci/rust:1.43.1-buster
    resource_class: small

commands:
  print_rust_version:
    steps:
      - run:
          name: Printing rust version
          command: |
            rustup --version
            rustc --version
            cargo --version
  restore_cargo_cache:
    steps:
      - restore_cache:
          keys:
            - cargo-cache-v1-{{ .Branch }}-{{ checksum "Cargo.lock" }}
            - cargo-cache-v1-{{ .Branch }}
            - cargo-cache-v1-
  save_cargo_cache:
    steps:
      - save_cache:
          paths:
            - ~/.cargo/registry
          key: cargo-cache-v1-{{ .Branch }}-{{ checksum "Cargo.lock" }}

jobs:
  rust-fmt:
    executor: rust
    steps:
      - checkout
      - print_rust_version
      - restore_cargo_cache
      - run:
          name: Running cargo fmt
          command: cargo fmt --all -- --check
      - save_cargo_cache
  rust-lint:
    executor: rust
    steps:
      - checkout
      - print_rust_version
      - restore_cargo_cache
      - run:
          name: Installing clippy
          command: rustup component add clippy
      - run:
          name: Running cargo check
          command: cargo check --workspace --all-targets
      - run:
          name: Running cargo clippy
          command: cargo clippy --all --all-targets -- -D warnings
      - save_cargo_cache
  rust-test:
    executor: rust
    steps:
      - checkout
      - print_rust_version
      - restore_cargo_cache
      - run:
          name: Running cargo test
          command: cargo test --all --all-targets
      - save_cargo_cache
  rust-coverage:
    executor: rust
    steps:
      - checkout
      - print_rust_version
      - restore_cargo_cache
      - run:
          name: Installing Rust nightly
          command: rustup install nightly
      - run:
          name: Running cargo test (on nightly)
          command: |
            export CARGO_INCREMENTAL=0
            export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off"
            cargo +nightly build --all --all-targets --all-features
            cargo +nightly test --all --all-targets --all-features
      - run:
          name: Installing grcov (v0.5.13)
          command: |
            curl --proto '=https' --tlsv1.2 -sSf -L https://github.com/mozilla/grcov/releases/download/v0.5.15/grcov-linux-x86_64.tar.bz2 | tar -xjf -
            ./grcov --version
      - run:
          name: Running grcov
          command: |
            ./grcov ./target/debug/ -s . -t html --llvm --branch --ignore-not-existing -o ./coverage/
            ./grcov ./target/debug/ -s . -t lcov --llvm --branch --ignore-not-existing -o lcov.info
      - save_cargo_cache
      - store_artifacts:
          path: ./coverage/
      - run:
          name: Uploading coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash) -f lcov.info -n "${CIRCLE_BUILD_NUM}"

workflows:
  rust-fmt:
    jobs:
      - rust-fmt
  rust-lint:
    jobs:
      - rust-lint
  rust-test:
    jobs:
      - rust-test
      - rust-coverage
